project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .

preserve_hierarchy: true

files:
  - source: _locale/**/LC_MESSAGES/*.po
    translation: _locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
