name: Deploy documents

on:
  push:
    branches:
      - main
      - 'doc/*'
    paths:
      - 'doc/**'
      - '.github/workflows/doc.yaml'
  workflow_dispatch:

env:
  languages: 'ja'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-sphinx

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-intl

      - name: Find the destination
        id: name
        run: |
          ref_name='${{ github.ref_name }}'
          ref_name_base="$(basename "$ref_name")"

          case "$ref_name_base" in
            *.* | *.*.*) version_dir="$ref_name_base" ;;
            *)           version_dir="devel" ;;
          esac

          echo "version_dir=${version_dir}" >> $GITHUB_OUTPUT

      - name: gettext
        run: |
          languages='${{ env.languages }}'

          cd doc

          sphinx-build -b gettext . _gettext
          for lang in ${languages}; do
            sphinx-intl update -p _gettext -l $lang
          done

      - name: upload and download Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          push_translations: false
          config: doc/crowdin.yaml
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build HTML files
        run: |
          languages='${{ env.languages }}'
          version_dir='${{ steps.name.outputs.version_dir }}'

          set -e

          cd doc
          rm -rf "../gh-pages/doc/$version_dir"
          sphinx-build -b html . "../gh-pages/doc/$version_dir"

          for lang in ${languages}; do
            rm -rf "../gh-pages/doc/$lang/$version_dir"
            sphinx-build -b html -D language=$lang . "../gh-pages/doc/$lang/$version_dir"
          done

      - name: upload
        run: |
          version_dir='${{ steps.name.outputs.version_dir }}'

          set -e
          h=$(git log -1 --format='%h')

          cd gh-pages

          if git status | grep 'nothing to commit'; then
            exit 0
          fi

          git config --global user.email '780600+norihiro@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

          git add "doc/$version_dir" doc/*/"$version_dir"
          git commit -m "doc/*/$version_dir: Generated from $h"

          git push
