name: Mypy

on:
  push:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt

      - run: |
          mypy --install-types --non-interactive src/
