name: Package

on:
  push:
    branches: ['*']
    tags: ['*']
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'test/**'

env:
  tagName: ${{ contains(github.ref_name, '/') && 'artifact' || github.ref_name }}

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: pyinstaller
        shell: pwsh
        run: |
          pip install .
          $PyInstallerArgs = @(
            '--name', 'slidetextbridge'
            'src/slidetextbridge/core/main.py'
          )
          pyinstaller.exe @PyInstallerArgs

      - name: pip-licenses
        run: |
          pip install pip-licenses
          pip-licenses.exe --from=mixed --format=plain-vertical --with-license-file --no-license-path --output-file dist/slidetextbridge/LICENSES.txt

      - name: datafile
        run: |
          copy data/basic-config.yaml dist/slidetextbridge/config.yaml

      - name: archive
        shell: pwsh
        run: |
          cd dist
          $compress = @{
            Path = "slidetextbridge\*"
            DestinationPath = "slidetextbridge-${{ env.tagName }}-Windows-x64.zip"
            Force = $true
          }
          Compress-Archive @compress

      - run: |
          dist/slidetextbridge/slidetextbridge.exe -h

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.tagName }}-windows
          path: dist/slidetextbridge*.zip

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: ['windows']
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.tagName }}-windows

      - uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          draft: true
          files: slidetextbridge*.zip
          generate_release_notes: true
