name: Package PyPI

on:
  push:
    branches: ['*']
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Build the package
        run: |
          python -m venv .venv-build
          . .venv-build/bin/activate
          pip install build
          python -m build
          ls -l dist/

      - name: Test
        run: |
          python -m venv --system-site-packages .venv-test
          . .venv-test/bin/activate
          pip install ./dist/slidetextbridge-*.whl
          python -m unittest discover test/

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/p/slidetextbridge
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
